---
title: "EstCrimen"
author: "Sergio Solano"
date: "26 de marzo de 2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

# Carga paquetes

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, cache = TRUE)
rm(list = ls())
library("lubridate") # Fechas
library("readxl") # Importar excel
library("magrittr") # pipes
library("purrr") # Listas
library("dplyr") # Data handling
library("tidyr") # Data handling
library("knitr") # Imprimir pdf
library("ggplot2") # Graficas
library("stringr") # Texto
library("curl") #Descargar desde internet
library("arules") # Crear intervalos
library("RColorBrewer") # Gráficas
library("colorRamps") # Gráficas
library("wesanderson") # Gráficas
library("xtable") # tabla
library("xts")

```

#Carga de archivos

```{r Carga xlsx}
#Estrucutra / Pendiente hacer independiente de la estrucutura
estrucutra <- c('Regional','Hombres_18-24',	'Mujeres_18-24',	'Hombres_25-29',	'Mujeres_25-29',	'Hombres_30-34',	'Mujeres_30-34',	'Hombres_35-39',	'Mujeres_35-39',	'Hombres_40-44',	'Mujeres_40-44',	'Hombres_45-49',	'Mujeres_45-49',	'Hombres_50-54',	'Mujeres_50-54',	'Hombres_55-59',	'Mujeres_55-59',	'Hombres_60-64',	'Mujeres_60-64',	'Hombres_65-69',	'Mujeres_65-69',	'Hombres_>69',	'Mujeres_>69')

# Listar archivos 
archivos <- list.files(pattern="xls")
archivos <- archivos[!grepl("DANE",archivos)]
n = length(archivos)

#Crear lista que se va a llenar con los archivos
Inpecxlsx = list()

#Leer archivos
for (i in 1:n) {
  hojas <- excel_sheets(archivos[i])
  hoja <- hojas[grepl("EDAD",hojas)]
  temporal <- as.data.frame(read_excel(archivos[i], sheet = hoja, range = "A8:W14"))
  colnames(temporal) <- estrucutra
  largo <- dim(temporal)[1]
  temporal$documento <- rep(archivos[i],largo)
  #print(paste(class(temporal[,2]),archivos[i],sep=" "))
  Inpecxlsx[[i]] <- list(temporal)
}
rm(temporal)
```

#Preprocesamiento
```{r a data.frame}
######## Agregar columna de fecha y poner en formato BD por fecha, edad y sexo

### Transformar a dataframe uniendo listas de cada archivo
Inpecxlsx %>%  map_df(bind_rows) -> base_inpecxlsx

#%>% filter(grepl("TOTAL",Regional)|grepl("Total",Regional))


#### Crear vectores de meses y año
months <- data.frame(month_text = c ("ENERO","FEBRERO","MARZO","ABRIL","MAYO","JUNIO","JULIO","AGOSTO","SEPTIEMBRE","OCTUBRE","NOVIEMBRE","DICIEMBRE"),month_number = seq(1:12))
year <- c('2016','2017','2018')


#### Separar nombre del archivo en texto
lista <- str_split(unique(base_inpecxlsx$documento)," ")
#### Indexar por documento
names(lista) <- as.vector(unique(base_inpecxlsx$documento))

#### convertir a data.frame
doc_date <- data.frame(documento = rep(names(lista), sapply(lista, length)),
                 palabra = unlist(lista))

#### Eliminar extensión del archivo
doc_date$palabra <-  gsub(".xlsx","",doc_date$palabra)
doc_date$palabra <-  gsub(".xls","",doc_date$palabra)

#### Crear vectores de mes y año
doc_date %>% dplyr::filter(palabra %in% months[,1]) -> doc_month
doc_date %>% dplyr::filter (palabra %in% year) -> doc_year
colnames(doc_month) <- c("documento","month_text")
colnames(doc_year) <- c("documento","year")

#### Concatenar base de Inpec con mes y año para crear fecha
base_inpecxlsx %>% left_join(doc_month,by = NULL) %>% left_join(months,by=NULL) %>% left_join(doc_year)%>% mutate(fecha = as.Date(paste(year,month_number,15, sep ="/"),"%Y/%m/%d")) -> Inpecxlsx_date

#### Poner en formato indexado por edad y fecha
Inpecxlsx_date %>% dplyr::select(-documento, -month_text, -month_number, -year) %>%  gather(Edad,Poblacion,-Regional, -fecha) -> InpecEdad_tidyTotal

#### Columnas de sexo y edad 
Edad_genero <- as.data.frame(str_split_fixed(InpecEdad_tidyTotal$Edad,"_",2))
InpecEdad_tidyTotal <- cbind(InpecEdad_tidyTotal,Edad_genero)
colnames(InpecEdad_tidyTotal) <- c("Region","Fecha","SexoEdad","Poblacion","Sexo","Edad")
InpecEdad_tidyTotal %>%  group_by(Fecha,SexoEdad,Sexo,Edad) %>% summarise(Poblacion=sum(Poblacion)) -> InpecEdad_tidy

InpecEdad_tidyTotal %>%  group_by(Fecha) %>% summarise(Poblacion=sum(Poblacion)) -> InpecEdad_tidy2
```


# Estadística descriptiva

```{r inpec_edad_genero1, fig.width=7}
## Gráfica 
InpecEdad_tidy %>% ggplot() + geom_line(aes(x=Fecha, y = Poblacion, colour = Edad )) + facet_wrap(~Sexo, ncol = 2, scales = "free") + ylab("Población privada de la libertad") + theme_minimal()-> gginpec_edad_genero1
gginpec_edad_genero1
#ggplotly(gato)
```

```{r gginpec_edad_genero_region, fig.height=10, fig.width=8}
InpecEdad_tidyTotal %>%  group_by(Fecha,SexoEdad,Sexo,Edad,Region) %>% summarise(Poblacion=sum(Poblacion)) -> InpecEdadRegion_tidy

InpecEdadRegion_tidy %>% ggplot() + geom_line(aes(x=Fecha, y = Poblacion, colour = Edad )) + facet_wrap(Region~Sexo, ncol=2,scales = "free") + ylab("Población privada de la libertad") + theme_minimal()-> gginpec_edad_genero_region1
gginpec_edad_genero_region1
```


```{r gginpec_edad_genero2}
InpecEdad_tidy %>% dplyr::filter(Fecha == as.Date("2016/06/15","%Y/%m/%d")) %>% ggplot() + geom_bar(aes(x=Edad, y = if_else(Sexo=="Hombres", -Poblacion,Poblacion), fill = Sexo), stat="identity") + coord_flip() +theme_minimal() + xlab("Edad")+ ylab("Población privada de la libertad-Junio 2017") + scale_y_continuous(labels = abs) + facet_wrap(~Fecha,ncol=1) +  scale_fill_manual(values = wes_palette("Moonrise3")) + labs(fill = "Género") -> gginpec_edad_genero2

gginpec_edad_genero2
```

```{r inpec_edad_genero3, fig.height=9, fig.width=8}
InpecEdad_tidy %>% ggplot() + geom_line(aes(x=Edad, y = Poblacion, group = paste(Sexo,Fecha,sep=""), colour = as.character(Fecha))) + theme_minimal() + xlab("Edad")+ ylab("Población privada de la libertad") + facet_wrap(~ Sexo,ncol=1, scales = "free") +theme(legend.title=element_blank(), legend.position="right")  -> gginpec_edad_genero3
gginpec_edad_genero3 
```

```{r inpec_edad_generoregion2, fig.height=12, fig.width=9}
InpecEdadRegion_tidy %>% ggplot() + geom_line(aes(x=Edad, y = Poblacion, group = paste(Sexo,Fecha,sep=""), colour = Fecha)) + theme_minimal() + xlab("Edad")+ ylab("Población privada de la libertad") + facet_wrap(Region ~ Sexo,ncol=2, scales = "free") +theme(legend.title=element_blank(), legend.position="right",axis.text.x = element_text(angle = 90, hjust = 1))  -> gginpec_edad_generoregion2
gginpec_edad_generoregion2 
```

# Carga datos Dane
```{r carga dane pry edad}
#### PROYECCIONES DE POBLACIÓN DANE

# Descargar archivo de la página del dane ## link desactualizado
#url <- "https://www.dane.gov.co/files/investigaciones/poblacion/proyepobla06_20/proyecciones-nivel-nacional-departamental-por-sexo-y-edades-simples-hasta-80-anos-y-mas.xls"
destfile <- "POB_PRY_DANE_EDAD.xls"
#curl_download(url, destfile)

# Carga de archivo de proyección por edad
base_pry_dane_edad <- as.data.frame(read_excel(destfile, range = "E12:IQ28"))

# Indexar por EdadGenero, tomar totales por cotrol
base_pry_dane_edad %>% gather(EdadGenero,Poblacion,-Año) -> base_pry_dane_edad_tidy

# Indexar por EdadGenero, eliminar totales.
base_pry_dane_edad_tidy %>% dplyr::filter(EdadGenero %in% c('Total Total','Hombres Total','Mujeres Total')) %>% spread(EdadGenero,Poblacion)-> base_pry_dane_totales

# Indexar por EdadGenero, eliminar totales.
base_pry_dane_edad_tidy %>% dplyr::filter(!(grepl("Total",EdadGenero))) -> base_pry_dane_edades

Edad_genero_dane <- as.data.frame(str_split_fixed( base_pry_dane_edades$EdadGenero," ",2))

base_pry_dane_edades <- cbind(base_pry_dane_edades, Edad_genero_dane)
colnames(base_pry_dane_edades) <- c("Year","EdadGenero","Poblacion_pry","Sexo","EdadYear")

base_pry_dane_edades$EdadYear <- as.integer(base_pry_dane_edades$EdadYear)

# Se crean rangos iguales a los de la población INPEC
base_pry_dane_edades$Edad <- discretize(base_pry_dane_edades$EdadYear, method = "fixed", breaks = c(-Inf,18, seq(from=25,to=70,by = 5),Inf),labels = c("0-17","18-24","25-29","30-34","35-39","40-44","45-49","50-54","55-59","60-64","65-69", ">69"))

#Crear columna Fecha 
base_pry_dane_edades %<>%  mutate(Fecha = as.Date(paste(Year,"06","15",sep="/"),"%Y/%m/%d"))

dane_edades <-base_pry_dane_edades %>% group_by(Fecha,Edad,Sexo) %>% summarise(Poblacion_pry=sum(Poblacion_pry))
```

# Preprocesamiento DANE e INPEC

```{r unir DANE e INPEC}
InpecEdad_tidy %>% left_join(dane_edades, by = c("Fecha"="Fecha","Edad"="Edad","Sexo"="Sexo")) %>% mutate(tasa_encarcelamiento=Poblacion*100000/Poblacion_pry) -> InpecDane
```

```{r gginpec_edad_generotasa1}
InpecDane %>% dplyr::filter(Fecha == as.Date("2016/06/15","%Y/%m/%d")) %>% ggplot() + geom_bar(aes(x=Edad, y = if_else(Sexo=="Hombres", -tasa_encarcelamiento,tasa_encarcelamiento), fill = Sexo), stat="identity") + coord_flip() +theme_minimal() + xlab("Edad")+ ylab("Tasa de encarcelamiento a Junio 2016") + scale_y_continuous(labels = abs) + facet_wrap(~Fecha,ncol=1) +  scale_fill_manual(values = wes_palette("Moonrise3")) + labs(fill = "Género")-> gginpec_edad_genero2 

gginpec_edad_genero2
```

```{r inpec_edad_generotasa2, fig.height=7}
InpecDane %<>% dplyr::filter(Fecha %in% c(as.Date("2017/06/15","%Y/%m/%d"), as.Date("2016/06/15","%Y/%m/%d")))  
InpecDane %>%  ggplot() + geom_line(aes(x=Edad, y = tasa_encarcelamiento, group = paste(Sexo,Fecha,sep=""), colour = as.character(Fecha))) + theme_minimal()+ xlab("Edad") + ylab("Tasa de encarcelamiento") + facet_wrap(~ Sexo,ncol=1, scales = "free") + theme(legend.title=element_blank(), legend.position="top") -> gginpec_edad_genero4
gginpec_edad_genero4
```

# Proyecciones DANE
```{r Proyecciones_DANE}
#dane_edades %>%filter(!(Edad %in% c("0-17"))) %>% ggplot() + geom_line(aes(x=Fecha,y=Poblacion_pry,colour = Edad)) + facet_wrap(~Sexo) + theme_minimal()


InpecDane %>% dplyr::filter (Fecha == as.Date("2016/06/15","%Y/%m/%d"))%>% group_by(Sexo,Edad) %>% summarise(tasa_encarcelamiento=sum(tasa_encarcelamiento)) -> InpecDaneTasa

dane_edades %>% left_join(InpecDaneTasa) %>% dplyr::filter(!(tasa_encarcelamiento %in% c(NA))) %>% mutate(PobCar_pry = Poblacion_pry*tasa_encarcelamiento/100000) -> DaneInpecPry

DaneInpecPry %>% dplyr::filter(!(Edad %in% c("0-17"))) %>% ggplot() + geom_area(aes(x=Fecha,y=PobCar_pry,fill = factor(Edad,levels=rev(levels(factor(Edad))))), stat="identity") + facet_wrap(~Sexo, scales = "free") + theme_minimal() + labs(y = "Proyección de población privada de la libertad", fill = "Edad")  + scale_fill_manual(values = colorRampPalette(brewer.pal(11, "Paired"))(11)) -> ggInpecDanepry

ggInpecDanepry
```

```{r población real}
# carga población
# Datos de población encarcelada en Junio 2017 # Comparar con datos oficiales
ppl_gen <- read.csv("ppl_gen.csv")
ppl_gen %<>% filter(mes == 6, anio >= 2005, anio < 2017) 
ppl_gen %<>% mutate(Date = as.Date(paste(anio,mes,"15", sep = "/"),"%Y/%m/%d")) %>% select(hombres,mujeres,Date)
colnames(ppl_gen) <- c("Hombres","Mujeres","Fecha")
ppl_gen %<>% gather(Sexo,Poblacion,-Fecha) 
```

#Proyección ajustada
```{r factor ajuste}
DaneInpecPry %>% group_by(Fecha, Sexo) %>% summarise(Pry_ppl_base = sum(PobCar_pry)) %>% left_join(ppl_gen, by = NULL) %>% mutate(Ajuste = Poblacion/Pry_ppl_base) %>% select(Fecha, Sexo, Ajuste) -> Pry

Pry[is.na(Pry$Ajuste),'Ajuste'] <- 1
```

```{r Proyeccion ajustada}
DaneInpecPry %>% left_join (Pry, by = NULL) %>% mutate(ppl_pry_aju = PobCar_pry*Ajuste) %>% mutate(tasa_pry_aju = ppl_pry_aju/Poblacion_pry*100000)-> DaneInpecPryAju

DaneInpecPryAju %>% dplyr::filter(!(Edad %in% c("0-17"))) %>% ggplot() + geom_area(aes(x=Fecha,y=ppl_pry_aju,fill = factor(Edad,levels=rev(levels(factor(Edad))))), stat="identity") + facet_wrap(~Sexo, scales = "free") + theme_minimal() + labs(y = "Proyección de población privada de la libertad ajustada", fill = "Edad")  + scale_fill_manual(values = colorRampPalette(brewer.pal(12, "Paired"))(12)) -> ggInpecDanepryAju

DaneInpecPryAju %>% dplyr::filter(!(Edad %in% c("0-17"))) %>% ggplot() + geom_line(aes(x=Fecha,y=tasa_pry_aju,colour = factor(Edad,levels=rev(levels(factor(Edad))))), stat="identity") + facet_wrap(~Sexo, scales = "free") + theme_minimal() + labs(y = "Proyección de tasa de encarcelamiento ajustada", fill = "Edad")  + scale_colour_manual(values = colorRampPalette(brewer.pal(12, "Paired"))(12)) + theme(legend.title = element_blank()) -> ggInpecDanepryAjuTasa
```

```{r ggInpecDanepryAju}
ggInpecDanepryAju
```

```{r ggInpecDanepryAjuTasa}
ggInpecDanepryAjuTasa
```

```{r tabla pry1} 
DaneInpecPry %>% group_by(Fecha, Sexo) %>% summarise(Pry_ppl_base = sum(PobCar_pry)) %>% left_join(ppl_gen, by = NULL) %>% mutate(Ajuste = Poblacion/Pry_ppl_base) %>% select(Fecha, Sexo, Poblacion, Pry_ppl_base, Ajuste) -> Pry2

Pry2$Fecha <- as.character(Pry2$Fecha)
xtable(Pry2, digits=c(0,0,0,0,0,2), caption = "PplAjuste", label = c("Proyección de la población carcelaria vs real"))
```

# Interpolación mensual

```{r}
# Totalizar proyección de hombres y mujeres por edad
pry_ppl_total <- DaneInpecPryAju %>% select(Sexo,ppl_pry_aju,Fecha, Edad) %>% group_by(Fecha) %>% summarise(Pry_total_ajus = sum(ppl_pry_aju))

# serie base
ts_base <- data.frame (Fecha = seq(as.Date("2005/6/15"),as.Date("2020/6/15"), by = "month"))

# unir series
ts_base %>% left_join(pry_ppl_total) -> pry_ppl_total_NA 

# Convertir a ts
ts_pry_ppl_total <- ts(pry_ppl_total_NA$Pry_total_ajus, start = c(2005, 6), frequency = 12)

# Ajustar serie de tiempo estructural
# Ajustar un modelo estado espacio en este método permitiróa incluir el efecto estacional.
sts_pry_ppl_total <- StructTS(ts_pry_ppl_total, type = c("trend"))
ts_smooth <- tsSmooth(sts_pry_ppl_total)

gato <- cbind(as.data.frame(ts_smooth[,1]),pry_ppl_total_NA)

gato %>% ggplot(aes(x = Fecha)) + geom_point(aes(y =Pry_total_ajus, colour = "Proyección")) + geom_line(aes(y = x, colour = "Suavizado")) + labs(x="Periodo", y = "Población carcelaria total") + theme_minimal() + theme(legend.title=element_blank(), legend.position="right")  
```



















